spring:
  datasource:
    url: jdbc:mysql://localhost:8080/test?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;noAccessToProcedureBodies=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle : 1
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxOpenPreparedStatements: 20
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  cache:
    ehcache:
      config: classpath:ehcache.xml
  application:
    name: power-spider

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
server:
  tomcat:
    uri-encoding: UTF-8
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:1001/eureka/


